version: 2.3.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.Common.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-CI'
dotnet_csproj:
  patch: true
  file: Common.props
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-CI'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    cd UnicodeInformation.Tests

    dotnet xunit
artifacts:
- path: UnicodeCharacterInspector\bin\Release
  name: UnicodeCharacterInspector
- path: UnicodeInformation\bin\Release\UnicodeInformation.*.nupkg
  name: NuGet
- path: UnicodeInformation\bin\Release\UnicodeInformation.*.snupkg
  name: NuGet Symbols
deploy:
- provider: NuGet
  api_key:
    secure: xz4w2pWoC4kB+DEzABgPGU+U9CaEjJp5aZmoIWZKDAUKB/LJtDL1MVThJnguiq/k
  skip_symbols: true
  artifact: NuGet;NuGet Symbols
  on:
    branch: master