version: '{build}'
os: Visual Studio 2015 Preview
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.Common.*
  assembly_version: 1.0.1.{build}
  assembly_file_version: 1.0.1.{build}
  assembly_informational_version: 1.0.1.{build}-CI
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: UnicodeCharacterInspector\bin\Release
  name: UnicodeCharacterInspector