version: '{build}'
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.Common.*
  assembly_version: 1.0.1.{build}
  assembly_file_version: 1.0.1.{build}
  assembly_informational_version: 1.0.1.{build}-CI
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: UnicodeCharacterInspector\bin\Release
  name: UnicodeCharacterInspector
deploy:
- provider: NuGet
  api_key:
    secure: S1uTeXbjD8eLun90hsjHjyf2TpjxOWS9YW7Z2Xu7Cg/sV5ogRm7OAr9P7E5lhueE
  skip_symbols: true
  on:
    branch: master